name: Release to env
on:
  repository_dispatch:
    types: [release-to-env]
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.client_payload.tag }}
          release_name: ${{ github.event.client_payload.tag }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: ${{ github.event.client_payload.prerelease }}
